### ISSUE TITLE
waybar .py file missing

### ISSUE THREAD

**Issue by Retaehc-pop** [MrVivekRajan/Hypr-Dots#3]
some of the on-click command doesn't work in waybar since it need a .py file which is not provided in the .config file

**Comment by MrVivekRajan** [comment]
It has been provided. Mostly there are 3 on-click options present in my waybar config combined of all the themes. One is to open rofi, one more is to open wlogout and the last one is to open eww-control center. The script for opening rofi and wlogout by on-click is present inside  ~/.config/hypr/scripts directory. And the script to open eww control center is present inside  ~/.config/eww/scripts directory
